const DEFAULT_API_BASE_URL = "https://middleware-aws-api.teexponent.com";
const API_BASE_URL = process.env.NEXT_PUBLIC_API_URL || DEFAULT_API_BASE_URL;
const API_ROOT = `${API_BASE_URL}/api/v1`;

const API_URL = Object.freeze({
    BASE_URL: API_BASE_URL,
    DEFAULT_BASE_URL: DEFAULT_API_BASE_URL,
    ROOT: API_ROOT,
    PLANS: "/plans",
    PLAN_BY_ID: (id) => `/plans/${id}`,
    PRICES: "/prices",
    PRICE_BY_ID: (id) => `/prices/${id}`,
    PRICES_IMPORT: "/prices/import",
    PRICES_EXPORT: "/prices/export",
    PRICE_ESTIMATE: "/prices/estimate",
    USERS: "/users",
    USER_LOGIN: "/users/login",
    USER_REGISTER: "/users/register",
    USER_SSO_REGISTER: "/users/sso-register",
    USER_ACTIVATE: "/users/activate",
    USER_RESEND_ACTIVATION: "/users/resend-activation",
    USER_FORGOT_PASSWORD: "/users/forgot-password",
    USER_CHANGE_PASSWORD: "/users/change-password",
    USER_COMPLETE_ONBOARDING: "/users/complete-onboarding",


    USER_SUBSCRIPTION: "/users/subscription",
    SUBSCRIPTION_CREATE: "/subscription/create",
    SUBSCRIPTION_INVOICES: "/subscription/invoices",
    WALLET: "/wallet",
    WALLET_CHECKOUT_SESSION: "/wallet/checkout-session",
    WALLET_CHECKOUT_SESSION_SYNC: "/wallet/checkout-session/sync",
    WALLET_TRANSACTION_INVOICE: (id) => `/wallet/transactions/${id}/invoice`,
    DASHBOARD_COUNTS: "/dashboard/counts",
    DASHBOARD_DISCREPANCY_TYPES: "/dashboard/discrepancy-types",
    DASHBOARD_CARRIER_ON_TIME_RATE: "/dashboard/carrier-on-time-rate",
    GENERAL_REGION: "/general/region",
    INTEGRATIONS: "/integrations",
    INTEGRATION_BY_ID: (id) => `/integrations/${id}`,
    CLIENTS: "/clients",
    CLIENT_BY_ID: (id) => `/clients/${id}`,
    WAREHOUSES: "/warehouses",
    WAREHOUSE_BY_ID: (id) => `/warehouses/${id}`,
    WAREHOUSES_EXPORT: "/warehouses/export",
    INVENTORY: "/inventory",
    INVENTORY_BY_ID: (id) => `/inventory/${id}`,
    DISCREPANCIES: "/discrepancies",
    DISCREPANCY_BY_ID: (id) => `/discrepancies/${id}`,
    DISCREPANCY_CLAIMS: (id) => `/discrepancies/${id}/claims`,
    CLAIMS: "/claims",
    CLAIM_BY_ID: (id) => `/claims/${id}`,
    ADDRESSES: "/addresses",
    ADDRESS_BY_ID: (id) => `/addresses/${id}`,
    ADDRESSES_FETCH: "/addresses/fetch",
    ORDERS: "/orders",
    ORDERS_SLA: "/orders/sla",
    ORDER_BY_ID: (id) => `/orders/${id}`,
    ORDER_QUOTE: "/orders/quote",
})

const PROJECT_URL = Object.freeze({
    HOME: "/",
    AUTH: "/auth",
    LOGIN: "/auth/login",
    REGISTER: "/auth/register",
    DASHBOARD: "/dashboard",
    CHANGE_PASSWORD: "/change-password",
    ONBOARDING: "/onboarding",
    SUBSCRIPTION: "/onboarding/subscription",
    DASHBOARD_CARRIERS: "/dashboard/carriers",
    DASHBOARD_ORDERS: "/dashboard/orders",
    DASHBOARD_INVENTORY: "/dashboard/inventory",
    DASHBOARD_ORDERS_CREATE: "/dashboard/orders/create",
    DASHBOARD_ORDERS_GENERATE: "/dashboard/generate",
    DASHBOARD_ORDER_GENERATE_BY_ID: (id) => `/dashboard/generate/${id}`,
    DASHBOARD_SUBSCRIPTION: "/dashboard/subscription",
    DASHBOARD_SUBSCRIPTION_UPGRADE: "/dashboard/subscription/upgrade",
    DASHBOARD_SLA_KPI: "/dashboard/sla-kpi",
    DASHBOARD_LABEL_GENERATOR: "/dashboard/label-generator",
    DASHBOARD_CLIENTS: "/dashboard/clients",
    DASHBOARD_PLANS: "/dashboard/plans",
    DASHBOARD_WAREHOUSES: "/dashboard/warehouses",
    DASHBOARD_ADDRESSES: "/dashboard/addresses",
    DASHBOARD_SLA_RULES: "/dashboard/sla-rules",
    DASHBOARD_BULK_IMPORT: "/dashboard/bulk-import",
    DASHBOARD_DISCREPANCIES: "/dashboard/discrepancies",
    DASHBOARD_CLAIMS: "/dashboard/claims",
    DASHBOARD_RATE_INTELLIGENCE: "/dashboard/rate-intelligence",
    DASHBOARD_RATE_CALCULATOR: "/dashboard/rate-calculator",
    DASHBOARD_PRICE_CHART: "/dashboard/price-chart",
    DASHBOARD_CREDIT_WALLET: "/dashboard/credit-wallet",
    DASHBOARD_NOTIFICATIONS: "/dashboard/notifications",
    DASHBOARD_SETTINGS: "/dashboard/settings",
    LOGO: "/assets/logo.png",
    GOOGLE_ICON: "/assets/google.svg",
    FACEBOOK_ICON: "/assets/facebook.svg",
})

export { API_URL, PROJECT_URL }
