export const ADDRESS_CONSTANTS = {
    FETCH_ADDRESSES_REQUEST: "FETCH_ADDRESSES_REQUEST",
    FETCH_ADDRESSES_SUCCESS: "FETCH_ADDRESSES_SUCCESS",
    FETCH_ADDRESSES_FAILURE: "FETCH_ADDRESSES_FAILURE",
    DELETE_ADDRESS_REQUEST: "DELETE_ADDRESS_REQUEST",
    DELETE_ADDRESS_SUCCESS: "DELETE_ADDRESS_SUCCESS",
    DELETE_ADDRESS_FAILURE: "DELETE_ADDRESS_FAILURE",
    RESET_ADDRESSES: "RESET_ADDRESSES"
};
