export const USER_LOGIN_CONSTANTS = {
    USER_LOGIN_REQUEST: "USER_LOGIN_REQUEST",
    USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
    USER_LOGIN_FAILURE: "USER_LOGIN_FAILURE",
    USER_LOGIN_VERIFY: "USER_LOGIN_VERIFY",
    USER_RESET_MESSAGE: "USER_RESET_MESSAGE",
    UPDATE_USER: "UPDATE_USER"
}

export const USER_LOGOUT_CONSTANTS = {
    USER_LOGOUT_REQUEST: "USER_LOGOUT_REQUEST",
    USER_LOGOUT_COMPLETE: "USER_LOGOUT_COMPLETE"
}