export const CHAT_CONSTANTS = {
    FETCH_SESSIONS_REQUEST: "FETCH_CHAT_SESSIONS_REQUEST",
    FETCH_SESSIONS_SUCCESS: "FETCH_CHAT_SESSIONS_SUCCESS",
    FETCH_SESSIONS_FAILURE: "FETCH_CHAT_SESSIONS_FAILURE",
    FETCH_HISTORY_REQUEST: "FETCH_CHAT_HISTORY_REQUEST",
    FETCH_HISTORY_SUCCESS: "FETCH_CHAT_HISTORY_SUCCESS",
    FETCH_HISTORY_FAILURE: "FETCH_CHAT_HISTORY_FAILURE",
    SEND_MESSAGE_REQUEST: "SEND_CHAT_MESSAGE_REQUEST",
    SEND_MESSAGE_SUCCESS: "SEND_CHAT_MESSAGE_SUCCESS",
    SEND_MESSAGE_FAILURE: "SEND_CHAT_MESSAGE_FAILURE",
    START_NEW_CHAT: "START_NEW_CHAT",
};
