export const CLIENT_CONSTANTS = {
    FETCH_CLIENTS_REQUEST: "FETCH_CLIENTS_REQUEST",
    FETCH_CLIENTS_SUCCESS: "FETCH_CLIENTS_SUCCESS",
    FETCH_CLIENTS_FAILURE: "FETCH_CLIENTS_FAILURE",
    DELETE_CLIENT_REQUEST: "DELETE_CLIENT_REQUEST",
    DELETE_CLIENT_SUCCESS: "DELETE_CLIENT_SUCCESS",
    DELETE_CLIENT_FAILURE: "DELETE_CLIENT_FAILURE",
    UPDATE_CLIENT_STATUS_REQUEST: "UPDATE_CLIENT_STATUS_REQUEST",
    UPDATE_CLIENT_STATUS_SUCCESS: "UPDATE_CLIENT_STATUS_SUCCESS",
    UPDATE_CLIENT_STATUS_FAILURE: "UPDATE_CLIENT_STATUS_FAILURE",
    RESET_CLIENTS: "RESET_CLIENTS"
};
