export const GENERAL_CONSTANTS = {
    FETCH_REGIONS_REQUEST: "FETCH_REGIONS_REQUEST",
    FETCH_REGIONS_SUCCESS: "FETCH_REGIONS_SUCCESS",
    FETCH_REGIONS_FAILURE: "FETCH_REGIONS_FAILURE",
    RESET_REGIONS: "RESET_REGIONS"
};
