export const INTEGRATION_CONSTANTS = {
    FETCH_INTEGRATIONS_REQUEST: "FETCH_INTEGRATIONS_REQUEST",
    FETCH_INTEGRATIONS_SUCCESS: "FETCH_INTEGRATIONS_SUCCESS",
    FETCH_INTEGRATIONS_FAILURE: "FETCH_INTEGRATIONS_FAILURE",
    RESET_INTEGRATIONS: "RESET_INTEGRATIONS"
};
