export const INVENTORY_CONSTANTS = {
    FETCH_INVENTORY_REQUEST: "FETCH_INVENTORY_REQUEST",
    FETCH_INVENTORY_SUCCESS: "FETCH_INVENTORY_SUCCESS",
    FETCH_INVENTORY_FAILURE: "FETCH_INVENTORY_FAILURE",
    DELETE_INVENTORY_REQUEST: "DELETE_INVENTORY_REQUEST",
    DELETE_INVENTORY_SUCCESS: "DELETE_INVENTORY_SUCCESS",
    DELETE_INVENTORY_FAILURE: "DELETE_INVENTORY_FAILURE",
    RESET_INVENTORY: "RESET_INVENTORY"
};
