export const ORDER_CONSTANTS = {
    FETCH_ORDERS_REQUEST: "FETCH_ORDERS_REQUEST",
    FETCH_ORDERS_SUCCESS: "FETCH_ORDERS_SUCCESS",
    FETCH_ORDERS_FAILURE: "FETCH_ORDERS_FAILURE",
    DELETE_ORDER_REQUEST: "DELETE_ORDER_REQUEST",
    DELETE_ORDER_SUCCESS: "DELETE_ORDER_SUCCESS",
    DELETE_ORDER_FAILURE: "DELETE_ORDER_FAILURE",
    RESET_ORDERS: "RESET_ORDERS"
};
