export const ORDER_CONSTANTS = {
    FETCH_ORDERS_REQUEST: "FETCH_ORDERS_REQUEST",
    FETCH_ORDERS_SUCCESS: "FETCH_ORDERS_SUCCESS",
    FETCH_ORDERS_FAILURE: "FETCH_ORDERS_FAILURE",
    FETCH_SLA_DASHBOARD_REQUEST: "FETCH_SLA_DASHBOARD_REQUEST",
    FETCH_SLA_DASHBOARD_SUCCESS: "FETCH_SLA_DASHBOARD_SUCCESS",
    FETCH_SLA_DASHBOARD_FAILURE: "FETCH_SLA_DASHBOARD_FAILURE",
    FETCH_LABEL_QUOTES_REQUEST: "FETCH_LABEL_QUOTES_REQUEST",
    FETCH_LABEL_QUOTES_SUCCESS: "FETCH_LABEL_QUOTES_SUCCESS",
    FETCH_LABEL_QUOTES_FAILURE: "FETCH_LABEL_QUOTES_FAILURE",
    DELETE_ORDER_REQUEST: "DELETE_ORDER_REQUEST",
    DELETE_ORDER_SUCCESS: "DELETE_ORDER_SUCCESS",
    DELETE_ORDER_FAILURE: "DELETE_ORDER_FAILURE",
    RESET_ORDERS: "RESET_ORDERS"
};
