export const PLAN_CONSTANTS = {
    FETCH_PLANS_REQUEST: "FETCH_PLANS_REQUEST",
    FETCH_PLANS_SUCCESS: "FETCH_PLANS_SUCCESS",
    FETCH_PLANS_FAILURE: "FETCH_PLANS_FAILURE",
    CREATE_PLAN_REQUEST: "CREATE_PLAN_REQUEST",
    CREATE_PLAN_SUCCESS: "CREATE_PLAN_SUCCESS",
    CREATE_PLAN_FAILURE: "CREATE_PLAN_FAILURE",
    UPDATE_PLAN_REQUEST: "UPDATE_PLAN_REQUEST",
    UPDATE_PLAN_SUCCESS: "UPDATE_PLAN_SUCCESS",
    UPDATE_PLAN_FAILURE: "UPDATE_PLAN_FAILURE",
    DELETE_PLAN_REQUEST: "DELETE_PLAN_REQUEST",
    DELETE_PLAN_SUCCESS: "DELETE_PLAN_SUCCESS",
    DELETE_PLAN_FAILURE: "DELETE_PLAN_FAILURE",
    UPDATE_PLAN_STATUS_REQUEST: "UPDATE_PLAN_STATUS_REQUEST",
    UPDATE_PLAN_STATUS_SUCCESS: "UPDATE_PLAN_STATUS_SUCCESS",
    UPDATE_PLAN_STATUS_FAILURE: "UPDATE_PLAN_STATUS_FAILURE",
    RESET_PLANS: "RESET_PLANS"
};
