export const PRICE_CONSTANTS = {
    FETCH_PRICES_REQUEST: "FETCH_PRICES_REQUEST",
    FETCH_PRICES_SUCCESS: "FETCH_PRICES_SUCCESS",
    FETCH_PRICES_FAILURE: "FETCH_PRICES_FAILURE",
    CREATE_PRICE_REQUEST: "CREATE_PRICE_REQUEST",
    CREATE_PRICE_SUCCESS: "CREATE_PRICE_SUCCESS",
    CREATE_PRICE_FAILURE: "CREATE_PRICE_FAILURE",
    UPDATE_PRICE_REQUEST: "UPDATE_PRICE_REQUEST",
    UPDATE_PRICE_SUCCESS: "UPDATE_PRICE_SUCCESS",
    UPDATE_PRICE_FAILURE: "UPDATE_PRICE_FAILURE",
    DELETE_PRICE_REQUEST: "DELETE_PRICE_REQUEST",
    DELETE_PRICE_SUCCESS: "DELETE_PRICE_SUCCESS",
    DELETE_PRICE_FAILURE: "DELETE_PRICE_FAILURE",
    IMPORT_PRICES_REQUEST: "IMPORT_PRICES_REQUEST",
    IMPORT_PRICES_SUCCESS: "IMPORT_PRICES_SUCCESS",
    IMPORT_PRICES_FAILURE: "IMPORT_PRICES_FAILURE",
    RESET_PRICES: "RESET_PRICES"
};
