export const SETTINGS_CONSTANTS = Object.freeze({
    FETCH_SETTINGS_REQUEST: "FETCH_SETTINGS_REQUEST",
    FETCH_SETTINGS_SUCCESS: "FETCH_SETTINGS_SUCCESS",
    FETCH_SETTINGS_FAILURE: "FETCH_SETTINGS_FAILURE",
    UPDATE_SETTINGS_REQUEST: "UPDATE_SETTINGS_REQUEST",
    UPDATE_SETTINGS_SUCCESS: "UPDATE_SETTINGS_SUCCESS",
    UPDATE_SETTINGS_FAILURE: "UPDATE_SETTINGS_FAILURE",
});
