export const WALLET_CONSTANTS = {
    FETCH_WALLET_REQUEST: "FETCH_WALLET_REQUEST",
    FETCH_WALLET_SUCCESS: "FETCH_WALLET_SUCCESS",
    FETCH_WALLET_FAILURE: "FETCH_WALLET_FAILURE",
    RESET_WALLET: "RESET_WALLET"
};
