export const WAREHOUSE_CONSTANTS = {
    FETCH_WAREHOUSES_REQUEST: "FETCH_WAREHOUSES_REQUEST",
    FETCH_WAREHOUSES_SUCCESS: "FETCH_WAREHOUSES_SUCCESS",
    FETCH_WAREHOUSES_FAILURE: "FETCH_WAREHOUSES_FAILURE",
    DELETE_WAREHOUSE_REQUEST: "DELETE_WAREHOUSE_REQUEST",
    DELETE_WAREHOUSE_SUCCESS: "DELETE_WAREHOUSE_SUCCESS",
    DELETE_WAREHOUSE_FAILURE: "DELETE_WAREHOUSE_FAILURE",
    RESET_WAREHOUSES: "RESET_WAREHOUSES"
};
